# Generated by Django 5.0.6 on 2024-06-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Subtitle_ExtractSearch", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="subtitle_file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="Subtitle_ExtractSearch.video",
                    ),
                ),
            ],
        ),
    ]
